# This file is a template, and might need editing before it works on your project.
image: nikolaik/python-nodejs:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

pages:
  script:
    - apt-get install -y build-essential
    - yarn install
    - ./node_modules/.bin/gatsby build --prefix-paths
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
    

deploy:
 stage: deploy
 variables:
  S3_BUCKET_NAME: "www.iamvish.me"
 script:
  - pip install awscli
  - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY npm run deploy
 only: 
  - master