# This file is a template, and might need editing before it works on your project.
image: nikolaik/python-nodejs:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

pages:
  script:
    - yarn install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master
    
build:
 stage: build
 script:
  npm run build
 rules: 
  - if: '$CI_COMMIT_BRANCH == "master"'
  - if: '$CI_MERGE_REQUEST_ID'

deploy:
 stage: deploy
 variables:
  S3_BUCKET_NAME: "www.iamvish.me"
 script:
  - pip install awscli
  - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY npm run deploy
 only: 
  - master