# This file is a template, and might need editing before it works on your project.
image: nikolaik/python-nodejs:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

pages:
  script:
    - yarn install
    - ./node_modules/.bin/gatsby build --prefix-paths
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
    

deploy:
 stage: deploy
 script:
  - pip install awscli
  - aws s3 sync ./public s3://www.iamvish.me
 only: 
  - master